import type { Metadata } from "next";
import { josefin_sans } from "@/public/fonts/fonts";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Headingbar from "@/components/Headingbar";
import Footer from "@/components/Footer";
import Subfooter from "@/components/Subfooter";
import Logo_bar from "@/components/Logo_bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={josefin_sans.className}>
      <body>
        <Headingbar />
        <Navbar />
        {children}
        <Logo_bar />
        <Footer />
        <Subfooter />
      </body>
    </html>
  );
}
